services:
  - type: worker
    name: telegram-movie-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false

runtime: python
buildCommand: pip install -r requirements.txt
startCommand: python main.py
env:
  - key: PYTHON_VERSION
    value: 3.11.7
