services:
  - type: web
    name: telegram-movie-bot
    env: python
    plan: free
    buildCommand: pip install --only-binary=:all: -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: BOT_TOKEN
        sync: false   # you’ll add this manually in Render Dashboard
      - key: CHANNEL_ID
        sync: false   # you’ll add this manually in Render Dashboard
